---
name: Run integration tests

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "Target environment"
        required: true
        type: string
        default: 'development'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./chapter_4

env:
  TICKETS_DATABASE_URL: postgresql+psycopg://train:train@db:x5x4x3x2/train

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e '.[dev]'

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
